name: "sonarqube"
repository: github.com/atanev/trivy-plugin-sonarqube
version: "v0.0.1"
maintainer: umax
summary: "Convert Trivy JSON report to SonarQube format"
description: |-
  A Trivy plugin that converts JSON report to SonarQube compatible format (https://docs.sonarqube.org/latest/analysis/generic-issue/).
  Usage: trivy sonarqube TRIVY-REPORT > SONARQUBE-REPORT
platforms:
  - uri: https://github.com/atanev/trivy-plugin-sonarqube/releases/download/v0.0.1/trivy-plugin-sonarqube-0.0.1.tar.gz
    bin: sonarqube.py
